### ISSUE TITLE
[1.18] Crash with our mods together

### ISSUE THREAD

**Issue by kwpugh** [nicguzzo/deepslateinstamine_fabric#2]
log:  https://gist.github.com/kwpugh/e44e16854b315ce926ad24e046bee954

the game crashes on the first if() conditional within cannMine(), with a null on the item stack, which seems unusual.   I can't  see your 1.18 code, so no idea what you might be mixing into.

here is my hammer class:
`public class Hammer extends PickaxeItem
{
    public Hammer(ToolMaterial material, int attackDamage, float attackSpeed, Settings settings)
    {
        super(material, attackDamage, attackSpeed, settings);
    }

    boolean obsidianFlag;

    @Override
    public boolean canMine(BlockState state, World world, BlockPos pos, PlayerEntity playerIn)
    {
        if(!playerIn.isSneaking() && playerIn.getMainHandStack().isSuitableFor(world.getBlockState(pos)))
        {
            obsidianFlag = (state.getBlock() == Blocks.OBSIDIAN || state.getBlock() == Blocks.CRYING_OBSIDIAN) ? true : false;
            AreaUtil.attemptBreakNeighbors(world, playerIn, 1, "hammer", obsidianFlag);
        }

        return true;
    }

    @Override
    public boolean isSuitableFor(BlockState state)
    {
        if (Items.DIAMOND_PICKAXE.isSuitableFor(state))
        {
            return true;
        }

        return Items.DIAMOND_PICKAXE.getMiningSpeedMultiplier(null, state) > 1.0f;
    }

    @Override
    public void appendTooltip(ItemStack itemStack, World world, List<Text> tooltip, TooltipContext tooltipContext)
    {
        tooltip.add(new TranslatableText("item.emerald_tools.hammer.tip1").formatted(Formatting.GREEN));
    }
}`

**Comment by nicguzzo** [comment]
Ok forge? It's basically the same code as fabric. I'll forgot to upload the branch, I'll do more testing asap.

**Comment by kwpugh** [comment]
this is on Fabric 1.18

**Comment by nicguzzo** [comment]
I've just added an if to check if itemstack comes null, uploading now, please test and let me know if it fixes it, it should.
```java
@Mixin(DiggerItem.class)
public class DiggerItemMixin {
	@Inject(at = @At("HEAD"), cancellable = true, method = "getDestroySpeed(Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/level/block/state/BlockState;)F")
	private void getDestroySpeed(ItemStack itemStack, BlockState blockState, CallbackInfoReturnable<Float> cir) {
		if(itemStack!=null && blockState !=null){
			Item item = itemStack.getItem();
			float speed = ((TieredItem) item).getTier().getSpeed();
			if (item.getDescriptionId().equals("item.minecraft.netherite_pickaxe")
					&& blockState.getBlock().getDescriptionId().equals("block.minecraft.deepslate")) {

				speed *= 4.3f;
				cir.setReturnValue(speed);
			}
		}
	}
}
```

**Comment by kwpugh** [comment]
Just  tested and no crash.  Thank you.
