### ISSUE TITLE
Server-side only gone?

### ISSUE THREAD

**Issue by ransompolley** [nicguzzo/deepslateinstamine_fabric#5]
Is the requirement for the mod to be on the client a new deal for 1.20.x? There are no other alternatives to this mod that I can find, and yet now this new change means I can't use it. I run a server with only server-side mods so that anyone with a vanilla client can connect and play. The mod worked flawlessly for me and my players in previous versions when only on the server. Thanks.

**Comment by nicguzzo** [comment]
Have you tried server only? It should work as before, the need for being present on client is for synchronization reasons.

**Comment by ransompolley** [comment]
Okay neat its still good. I was in the beginning process of updating mods & some infrastructure for my server, and saw the new "requirement" 
Finished with that now and the mod does still in fact work with a vanilla client, thanks for the clarification. 
Will be recommending the client side to my players :+1:
